title: Paully D
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made by Beyond the Pixel
        url: 'https://www.beyondthepx.com'
  header:
    bg_img: /images/9.jpg
    has_nav: true
    has_social: true
    logo_img: images/logo.png
    tagline: Gentleman of Adventure
    title: Paully D
  palette: green
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
